### ISSUE TITLE
adress-list not overwritten

### ISSUE THREAD

**Issue by njumaen** [multiduplikator/mikrotik_blocklist#2]
Hi,

due to the fact that address-list entries are not overwritten and break the import could you please provide import-files of

{ :do { /ip firewall address-list add address="1.1.1.1" list="blocklist"} on-error={ } }

One could set individual timeout by script, depending on the next fetch.

Just as an idea/experiment.

Reference to https://forum.mikrotik.com/viewtopic.php?t=191673

Thank you,

Ralf.

**Comment by multiduplikator** [comment]
I am not sure if I understand what you are suggesting.

In my script, I am basically removing all entries from the productive blocklist that do no longer exist in the new blocklist. And in the same pass, I am removing all entries that are in both blocklist from the new blocklist. Then, I add the remaining entries from the new blocklist to the productive blocklist.

So, I should never get into an overwrite situation...

What am I overlooking ... you got me curious now...

**Comment by multiduplikator** [comment]
Ohhh, you want the blocklist itself in the format you suggested, So you can simply overwrite the existing blocklist.

I could do that, but then my question is, what happens if IP addresses get removed from the blocklist. Would you then not accumulate garbage?

**Comment by njumaen** [comment]
I would set the timeout fitting to the frequency the fetch script is run e.g. by

 /ip firewall address-list set timeout="06:00:00" [find list="test"]

I'm curious how speed and memory consumption will be. :-)

**Comment by multiduplikator** [comment]
I still don't get it. Sorry, I am dumbfounded. I will produce the list in the format you suggested, So you can test and enlighten me later :)

**Comment by multiduplikator** [comment]
Added the files as you wanted them. Please check if they are syntactically correct. Let me know if you need changes...

[blocklist_test.rsc](https://github.com/multiduplikator/mikrotik_blocklist/blob/main/blocklist_test.rsc)
[blocklist_test_l.rsc](https://github.com/multiduplikator/mikrotik_blocklist/blob/main/blocklist_test_l.rsc)

**Comment by njumaen** [comment]
```
/tool fetch url="https://raw.githubusercontent.com/multiduplikator/mikrotik_blocklist/main/blocklist_test.rsc" mode=https dst-path=/disk1/blocklist.rsc
/import file-name=/disk1/blocklist.rsc
/ip firewall address-list set timeout="12:00:00" [find list="blocklist"]
```

works great!

Simple & fast. ;-)

Thank you!

**Comment by multiduplikator** [comment]
So after 12h the entries expire, I assume.

Now, if you fetch every 12h lets say, you import, and then set 12h expiration again. You set it on all entries in the list. I still dont understand how you prevent accumulation of old entries, since you set timeout on all entries in the list after importing...unless the timing is very very precise...and you know how long the fetch and import takes...

You might better do different scripts. 1 for fetch, then 1min later import, 1min later timout. Then you can set the timeout against something that is unlikely to vary in duration...

But well, it if works for you - I am happy.

You just have to tell me what to replace "test" with in the filename ;)

**Comment by njumaen** [comment]
good point. Maybe 11:59 then ;-)
test is OK for now, maybe something more meaningful later...

**Comment by multiduplikator** [comment]
Closing this, as it has been solved or is obsolete
