### ISSUE TITLE
Private IP subnet on list

### ISSUE THREAD

**Issue by njumaen** [multiduplikator/mikrotik_blocklist#6]
10.0.0.0/8 and 172.16.0.0/16 are on the blocklist.

I think they should not, as they are private subnets and often used for vpn, etc...

In my case for modem-router and vpn connections.

https://sourcedaddy.com/networking/private-subnets.html

so to be 'safe' you could add

/ip firewall address-list set [find list="prod_blocklist" address="10.0.0.0/8"] disabled=yes
/ip firewall address-list set [find list="prod_blocklist" address="172.16.0.0/12"] disabled=yes
/ip firewall address-list set [find list="prod_blocklist" address="192.168.0.0/16"] disabled=yes

after

:set newips

**Comment by theQuikest** [comment]
You're right in the fact the those ranges are private IP addresses, which makes it more justified to have them in the blocklist. Since no connection from or to the internet should have an address like that.

IMHO a better way is to set a firewall raw rule before the rule where you drop the blocklist like:
`/ip firewall raw add action=accept chain=prerouting comment="Allow local from default IP range LAN" in-interface-list=LAN    src-address-list=local_lan`
and adding the local lan addresses you use in a address list called "local_lan" like 
`/ip firewall address-list add address=10.0.10.0/24 comment="local IP range" list=local_lan`

This way you'll never have to look again and you're local lan keeps working.

**Comment by njumaen** [comment]
OK. good idea, but then why isn't 192.168.0.0/16 on the blocklist as well?

**All three** are RFC1918 address ranges...

**Comment by theQuikest** [comment]
If you set up the firewall rules according to Mikrotik advanced firewall setup you would have blocked 127.0.0.0/8, 192.0.0.0/24, 198.51.100.0/24 and 240.0.0.0/4 in RAW rules pre routing chain under 'bad_dst_ipv4'. They're special-purpose IP addresses under RFC6890.

**Comment by multiduplikator** [comment]
Yep. Its a question on where you place it.

This blocklist is designed to work with Mikrotik Advanced firewall, and needs to be used in the RAW prerouting chain.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/66225282/225903652-ae9b03ea-36e6-4e72-999c-77338b459c2f.png">

Effectively replacing "bad_ipv4" in IPv4 RAW Rules here:
https://help.mikrotik.com/docs/display/ROS/Building+Advanced+Firewall

I have wireguards, ovpns and sstps running no issue...

**Comment by theQuikest** [comment]
> I think they should not, as they are private subnets and often used for vpn, etc...
> 
> In my case for modem-router and vpn connections.
> 

Doe you use NAT on you're Mikrotik or do you have a modem-router in front does NAT? Because then you would need to let a private address through you're WAN connecting on you're Mikrotik.

**Comment by multiduplikator** [comment]
If that is the case, you can still leave the blocklist setup as prescribed above. You just need to add an explicit allow rule before going into the drop ruleset. Advantage is, that you can allow a very specific IP range for your individual purposes, blocking anything else.

But ideally, you should block already on "the real WAN"...

**Comment by multiduplikator** [comment]
@njumaen If you want, I can make a version for you removing the two line items from the list. Let me know.

**Comment by njumaen** [comment]
Thanks. It's now OK the way it is. Added an "allow" rule for my modem (MT is exposed host).

Cheers,

Ralf.
